version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: ./src

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: docs/requirements.txt
# formats:
#   - pdf
#   - epub